insert into task (task_name, task_description, task_date) values ('Street sweeping', 'Sweep streets in the area to maintain cleanliness', '2024-06-09');
insert into task (task_name, task_description, task_date) values ('Road safety awareness', 'Bring locals together to inform them about road safety', '2024-07-20');
insert into task (task_name, task_description, task_date) values ('Recycling program', 'Organize a program that will teach the residents proper recycling techniques', '2024-07-06');
insert into task (task_name, task_description, task_date) values ('Road maintenance', 'Inspect and fix broken roads in the community', '2024-08-06');
insert into task (task_name, task_description, task_date) values ('Community engagement workshop', 'Arrange residents in a community for a workshop that will improve their skills', '2024-08-16');
insert into task (task_name, task_description, task_date) values ('Energy Conservation Program', 'Organize a program that will inform residents on how to conserve energy', '2024-06-18');
insert into task (task_name, task_description, task_date) values ('Street sign repair', 'Repair broken street signs in the community', '2024-07-02');
insert into task (task_name, task_description, task_date) values ('Community clean-up', 'Gather volunteers together to clean public spaces', '2024-12-07');
insert into task (task_name, task_description, task_date) values ('Blood Donation Drive', 'Gather volunteers in the community to donate blood', '2024-12-15');
insert into task (task_name, task_description, task_date) values ('Fire safety awareness', 'Conduct fire drills to teach fire prevention to residents', '2024-09-05');
insert into task (task_name, task_description, task_date) values ('Community event organization', 'Arrange and bring residents together for a social event', '2024-05-30');
insert into task (task_name, task_description, task_date) values ('Youth mentorship program', 'Gather youths in the community for mentoring', '2024-12-19');
insert into task (task_name, task_description, task_date) values ('Neighborhood watch program', 'Gather volunteers to watch neighborhood to reduce crime', '2024-11-12');
insert into task (task_name, task_description, task_date) values ('Public space beautification', 'Procure necessary materials to beautify public spaces in the area', '2024-08-29');
insert into task (task_name, task_description, task_date) values ('Drainage clearing', 'Clean blocked drainages and canals in the area', '2024-11-03');
insert into task (task_name, task_description, task_date) values ('Public park maintenance', 'Inspect public parks to ensure that the area is safe and operating efficiently', '2024-10-01');
insert into task (task_name, task_description, task_date) values ('Trash collection', 'Collect accumulated trash and waste that are scattered in the area', '2024-07-25');
insert into task (task_name, task_description, task_date) values ('Public safety awareness', 'Gather residents in the community for a public safety awareness', '2024-11-27');
insert into task (task_name, task_description, task_date) values ('Festival', 'Organize various festive activities for the residents in the community', '2024-09-02');
insert into task (task_name, task_description, task_date) values ('Inter Barangay League', 'Arrange a sports tournament in the community for the youths', '2024-10-09');
insert into task (task_name, task_description, task_date) values ('Fashion show', 'Gather volunteers and arrange a venue for a fashion show', '2024-08-19');
insert into task (task_name, task_description, task_date) values ('Graffiti removal', 'Paint the walls to remove Graffiti', '2024-09-07');
insert into task (task_name, task_description, task_date) values ('Tree Planting', 'Find volunteers in the community for planting of trees in the area', '2024-06-10');
insert into task (task_name, task_description, task_date) values ('Public infrastructure improvement', 'Improve public infrastructures for the community', '2024-09-13');
insert into task (task_name, task_description, task_date) values ('Senior citizen assistance', 'Provide the monthly assistance of senior citizens for thier daily expenses', '2024-08-12');

insert into task (task_name, task_description, task_date) values ('Ayuda', 'Help the victims of the typhoon by giving foods and supplies', '2024-02-15');
insert into task (task_name, task_description, task_date) values ('Street market organization', 'Organize street vendors in the community', '2024-01-09');
insert into task (task_name, task_description, task_date) values ('Medical Assistance', 'Gather medical volunteers for a medical check-up for the residents', '2024-03-30');
insert into task (task_name, task_description, task_date) values ('Emergency preparedness training', 'Gather residents for an emergency preparedness training', '2024-04-01');
insert into task (task_name, task_description, task_date) values ('Community garden upkeep', 'Take care of local produce in the community', '2024-03-16');
insert into task (task_name, task_description, task_date) values ('Public health campaign', ' Organize campaign  and bring residents in the community to inform them about health threats', '2024-04-16');
insert into task (task_name, task_description, task_date) values ('Community center maintenance', 'Inspect community center if the area is safe and working efficiently', '2024-01-17');
insert into task (task_name, task_description, task_date) values ('Food Donation Drive', 'Encourage residents to donate foods for the needy', '2024-03-26');
insert into task (task_name, task_description, task_date) values ('General Meeting', 'Assemble all officials in the Barangay Hall for a meeting', '2024-04-29');
insert into task (task_name, task_description, task_date) values ('Community disaster response', 'Gather locals to teach them various techniques to save lives', '2024-04-19');
insert into task (task_name, task_description, task_date) values ('Street lighting repair', 'Repair broken street lights in the area to improve visibilty', '2024-03-21');
insert into task (task_name, task_description, task_date) values ('Emergency response training', 'Bring residents together for a training when there is an emergency', '2024-04-15');
insert into task (task_name, task_description, task_date) values ('Cultural heritage preservation', 'Safeguard cultural heritage to ensure its survival for future generations', '2024-01-28');
insert into task (task_name, task_description, task_date) values ('Water conservation campaign', 'Arrange this campaign to teach residents to conserve water', '2024-02-12');
insert into task (task_name, task_description, task_date) values ('Health and wellness program', 'Organize this program to improve residents health and wellness', '2024-02-07');
insert into task (task_name, task_description, task_date) values ('Art Contest', 'Conduct an art contest in the community for aspiring artists', '2024-04-28');
insert into task (task_name, task_description, task_date) values ('Book Donation Drive', 'Encourage locals in the community to donate thier old books', '2024-03-16');
insert into task (task_name, task_description, task_date) values ('Community Meeting', 'Gather residents to discuss recent issues that is happening in the community', '2024-02-08');
insert into task (task_name, task_description, task_date) values ('Educational Assistance', 'Give students their monthly educational assistance', '2024-04-27');
insert into task (task_name, task_description, task_date) values ('Libreng Tuli', 'Procure medical volunteers to conduct free circumcisions for the youths in the Barangay', '2024-03-25');
insert into task (task_name, task_description, task_date) values ('Day Care Center Maintenance', 'Inspect and clean day care center to ensure the safety of the children', '2024-01-08');
insert into task (task_name, task_description, task_date) values ('Animal Bite Awareness', 'Teach residents in the community on being aware about animal bites and the ways to cure them', '2024-02-05');
insert into task (task_name, task_description, task_date) values ('Environmental education program', 'Organize program to educate residents about the environment', '2024-04-14');
insert into task (task_name, task_description, task_date) values ('Trash Segregation', 'Collect trashes and segregate', '2024-02-20');
insert into task (task_name, task_description, task_date) values ('Dental Mission', 'Find medical volunteers to conduct dental mission for the residents in the community', '2024-01-30');
